---

- name: Installing apt-key
  apt_key: url=https://packages.microsoft.com/keys/microsoft.asc

- name: Import the NodeSource GPG key into apt
  apt_key: url=https://packages.microsoft.com/keys/microsoft.asc

- name: Add vscode deb repository
  apt_repository: repo='deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main' state=present

- name: Install vscode
  apt: pkg=code state=latest update_cache=yes
