---

- name: Installing apt-key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg


- name: Add deb repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: no

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install docker
  apt: pkg="{{ item }}" state=present
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Create Docker group
  group: name=docker state=present

- name: Add current user to Docker group
  user: name="{{ ansible_env.USER }}" groups=docker append=yes

- name: "Ensure Docker is {{ docker.start | ternary('started','stopped') }}"
  service: name=docker state={{ docker.start | ternary('restarted','stopped') }} enabled={{ docker.service_enabled }}

- name: Install docker-compose
  get_url: url="https://github.com/docker/compose/releases/download/1.9.0/docker-compose-Linux-x86_64" dest=/usr/local/bin/docker-compose force=no mode=0755
